### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by GraphiPerso** [linziyou0601/yugioh-card-maker#1]
Hi! I don't know how to use it, there is no instruction in the code and no test page :s

**Comment by linziyou0601** [comment]
This is a static website built using NuxtJS framework for users who can make custom Yu-Gi-Oh Cards. And using the JavaScript and Canvas to implement card drawing logic.

**Comment by GraphiPerso** [comment]
Is it possible to have the html or php page to use it please?
I don't understand japanese so I wanted to trad it to my language and use it

**Comment by linziyou0601** [comment]
I'm afraid I could not provide the html or php file because I just refactored it from pure html+javascript to NuxtJS last month and the old file's drawing logic is a bit bad.

However, the webpage that I just updated to support the multilingual "user interface." You can also add your language to the `ui.lang.json` file located in `/static` directory.
Only the language of the "card" cannot be changed due to the fonts and card face design. sorry for any inconvenience.

I had updated the readme file also
hope it helps you

**Comment by GraphiPerso** [comment]
Thanks!

Is it usable offline? how?

I didn't know this environement, is it better than html/php? more secure too?

**Comment by linziyou0601** [comment]
It is usable offline because most of the elements and modules of this project are installed locally by npm, except for some css, it imports Google Font.

VueJS a progressive JavaScript framework to develop the website. A web page with a lot of page elements has a huge structure. If all the data and views are mixed, and they are all mixed in HTML like traditional development, it will be very laborious to process them.
Also, this framework and implement data and function binding in html code. It can be easily integrated with third-party libraries or existing projects. Its bottom-up feature makes it more convenient and faster to develop the website.

And the NuxtJS is a framework based on VueJS, which can better render the server side, automatically generate routing, improved meta tag management and SEO improvements. Furthermore, they can also integrated with NodeJS Express server to build the server side API if you want.

**Comment by GraphiPerso** [comment]
basically lighter, better, stronger ? ^^ 

How can I use it? I can't open the index.vue on chrome directly? need another software? integrate the index.vue to a html page?

**Comment by linziyou0601** [comment]
Whether it is stronger varies from person to person, but I am more familiar with it. There are also many other front-end frameworks used by people such as AngularJS and ReactJS.

To start nuxtJS in dev mode, you need to download the nodeJS and npm on your computer. Then open the cmd (if you use Windows) and change to the project directory. Finally, input the command `npm run dev`. You may see the prompt that the website is hosted on http://localhost:3000

For more questions, you can move to Discussions tab of this repo to open a new discussion thread.
I just close this issue.
